### ISSUE TITLE
Update Physics Major

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook-area-data#86]
> Also 376 is no longer required, but 386 still is. 376 was replace with another elective, but i'm not sure about the requirements for that elective ( may need to be a 300 level). They updated last year, but they have yet to put it online. Another person you may want to ask is Professor Brian Borovsky. He's been the chair for the past few years and the major was changed under his direction.
> – Eric

---

> You need two electives; one of them must be a 300 level.The other elective cannot be a 100 level. 376 still exists as a course offering(works for the 300 level elective) but is no longer required for the major.
> — Spenser

**Comment by hawkrives** [comment]
@drewvolz: Don't you just *love* it when majors change without updating the website?

**Comment by drewvolz** [comment]
@hawkrives That's the nature of the beast.
